name: Publish Docker image

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: tttfrfr2/echonettester
          tags: |
            type=ref,event=branch
            type=ref,event=tag
        #- name: Set output
        #  id: vars
        #  run: | 
        #    if [ "${{ github.event_name }}" = 'release' ]; then
        #      echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        #    else
        #      echo ::set-output name=tag::latest
        #    fi

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            #tttfrfr2/echonettester:${{ steps.vars.outputs.tag }}
            tttfrfr2/echonettester:latest
            ${{ step.meta.outputs.tags }}
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
