name: Publish Docker image

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta 
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            tttfrfr2/echonettester
          tags: |
            latest
            type=ref,event=tag

      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            tttfrfr2/test:${{ steps.tag.outputs.result }}
            ${{ steps.meta.outputs.tags }}
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
